version: "3.9"
services: 
  web:
    depends_on: 
      - api
    build: ./frontend
    ports:
      - 3000:3000
    restart: always
    volumes: 
      - ./frontend/src:/app/src/
    networks: 
      - opnet
  api:
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 8000:80
    restart: always
    volumes: 
      - ./backend/wp-content:/var/www/html/wp-content/
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: octaposts
    networks:
      - opnet
  db:
    image: mysql:8.0.26
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: octaposts
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - opnet
networks:
  opnet:
volumes:
  db_data:
